version: '3.1'
services:
    postgres:
        image: 'postgres:11.1-alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql'
            - './docker/fill-tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql'
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=meteo
            - POSTGRES_DB=mountain-peak
        ports:
            - '52004:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '52000:80'

    php-fpm:
        build: docker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
